DROP TABLE IF EXISTS Plots;
CREATE TABLE Plots (
PlotID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
UserKey INT(11) NOT NULL
  REFERENCES Users(UserKey)
  ON DELETE CASCADE,
Location VARCHAR(50) NOT NULL,
pH VARCHAR(255),
Salt VARCHAR(255),
Phosphorus VARCHAR(255),
Potassium VARCHAR(255),
Tips MEDIUMTEXT,
Layout VARCHAR(2000),
ExpDate INT UNSIGNED);


DROP TABLE IF EXISTS PlotImages;
CREATE TABLE PlotImages (
PlotImgID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
PlotID INT UNSIGNED NOT NULL
  REFERENCES Plots(PlotID)
  ON DELETE NO ACTION,
Caption VARCHAR(255),
ImgURL VARCHAR(2000));
